//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logging_App.A1DataCheckService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A1DataCheckService.WellLogCheckSoap")]
    public interface WellLogCheckSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsExistProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IsExistProject(string year, string wellName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProjectYear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetProjectYear(string wellName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsExistWell", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsExistWell(string wellName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWellList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetWellList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProjectList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProjectList(string year);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WellLogCheckSoapChannel : Logging_App.A1DataCheckService.WellLogCheckSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WellLogCheckSoapClient : System.ServiceModel.ClientBase<Logging_App.A1DataCheckService.WellLogCheckSoap>, Logging_App.A1DataCheckService.WellLogCheckSoap {
        
        public WellLogCheckSoapClient() {
        }
        
        public WellLogCheckSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WellLogCheckSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellLogCheckSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellLogCheckSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string IsExistProject(string year, string wellName) {
            return base.Channel.IsExistProject(year, wellName);
        }
        
        public string GetProjectYear(string wellName) {
            return base.Channel.GetProjectYear(wellName);
        }
        
        public bool IsExistWell(string wellName) {
            return base.Channel.IsExistWell(wellName);
        }
        
        public System.Data.DataTable GetWellList() {
            return base.Channel.GetWellList();
        }
        
        public System.Data.DataTable GetProjectList(string year) {
            return base.Channel.GetProjectList(year);
        }
    }
}
