//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace Logging_App.WorkflowService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WorkflowServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModelBase))]
    public partial class WorkflowService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetActiveUserWorkflowTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWorkflowDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppointDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelSubmitReviewOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelReviewOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WorkflowService() {
            this.Url = global::Logging_App.Properties.Settings.Default.Logging_App_WorkflowService_WorkflowService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetActiveUserWorkflowTypesCompletedEventHandler GetActiveUserWorkflowTypesCompleted;
        
        /// <remarks/>
        public event GetWorkflowDataCompletedEventHandler GetWorkflowDataCompleted;
        
        /// <remarks/>
        public event SubmitReviewCompletedEventHandler SubmitReviewCompleted;
        
        /// <remarks/>
        public event ReviewCompletedEventHandler ReviewCompleted;
        
        /// <remarks/>
        public event AppointDataCompletedEventHandler AppointDataCompleted;
        
        /// <remarks/>
        public event CancelSubmitReviewCompletedEventHandler CancelSubmitReviewCompleted;
        
        /// <remarks/>
        public event CancelReviewCompletedEventHandler CancelReviewCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveUserWorkflowTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WorkflowType[] GetActiveUserWorkflowTypes() {
            object[] results = this.Invoke("GetActiveUserWorkflowTypes", new object[0]);
            return ((WorkflowType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveUserWorkflowTypesAsync() {
            this.GetActiveUserWorkflowTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetActiveUserWorkflowTypesAsync(object userState) {
            if ((this.GetActiveUserWorkflowTypesOperationCompleted == null)) {
                this.GetActiveUserWorkflowTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveUserWorkflowTypesOperationCompleted);
            }
            this.InvokeAsync("GetActiveUserWorkflowTypes", new object[0], this.GetActiveUserWorkflowTypesOperationCompleted, userState);
        }
        
        private void OnGetActiveUserWorkflowTypesOperationCompleted(object arg) {
            if ((this.GetActiveUserWorkflowTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveUserWorkflowTypesCompleted(this, new GetActiveUserWorkflowTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWorkflowData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Controller GetWorkflowData(WorkflowType type, string obj_id1, string obj_id2) {
            object[] results = this.Invoke("GetWorkflowData", new object[] {
                        type,
                        obj_id1,
                        obj_id2});
            return ((Controller)(results[0]));
        }
        
        /// <remarks/>
        public void GetWorkflowDataAsync(WorkflowType type, string obj_id1, string obj_id2) {
            this.GetWorkflowDataAsync(type, obj_id1, obj_id2, null);
        }
        
        /// <remarks/>
        public void GetWorkflowDataAsync(WorkflowType type, string obj_id1, string obj_id2, object userState) {
            if ((this.GetWorkflowDataOperationCompleted == null)) {
                this.GetWorkflowDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWorkflowDataOperationCompleted);
            }
            this.InvokeAsync("GetWorkflowData", new object[] {
                        type,
                        obj_id1,
                        obj_id2}, this.GetWorkflowDataOperationCompleted, userState);
        }
        
        private void OnGetWorkflowDataOperationCompleted(object arg) {
            if ((this.GetWorkflowDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWorkflowDataCompleted(this, new GetWorkflowDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitReview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SubmitReview(WorkflowType type, string target_loginname, string obj_id1, string obj_id2) {
            object[] results = this.Invoke("SubmitReview", new object[] {
                        type,
                        target_loginname,
                        obj_id1,
                        obj_id2});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitReviewAsync(WorkflowType type, string target_loginname, string obj_id1, string obj_id2) {
            this.SubmitReviewAsync(type, target_loginname, obj_id1, obj_id2, null);
        }
        
        /// <remarks/>
        public void SubmitReviewAsync(WorkflowType type, string target_loginname, string obj_id1, string obj_id2, object userState) {
            if ((this.SubmitReviewOperationCompleted == null)) {
                this.SubmitReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitReviewOperationCompleted);
            }
            this.InvokeAsync("SubmitReview", new object[] {
                        type,
                        target_loginname,
                        obj_id1,
                        obj_id2}, this.SubmitReviewOperationCompleted, userState);
        }
        
        private void OnSubmitReviewOperationCompleted(object arg) {
            if ((this.SubmitReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitReviewCompleted(this, new SubmitReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Review", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Review(WorkflowType type, WorkflowState state, string obj_id1, string obj_id2, string message) {
            object[] results = this.Invoke("Review", new object[] {
                        type,
                        state,
                        obj_id1,
                        obj_id2,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReviewAsync(WorkflowType type, WorkflowState state, string obj_id1, string obj_id2, string message) {
            this.ReviewAsync(type, state, obj_id1, obj_id2, message, null);
        }
        
        /// <remarks/>
        public void ReviewAsync(WorkflowType type, WorkflowState state, string obj_id1, string obj_id2, string message, object userState) {
            if ((this.ReviewOperationCompleted == null)) {
                this.ReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReviewOperationCompleted);
            }
            this.InvokeAsync("Review", new object[] {
                        type,
                        state,
                        obj_id1,
                        obj_id2,
                        message}, this.ReviewOperationCompleted, userState);
        }
        
        private void OnReviewOperationCompleted(object arg) {
            if ((this.ReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReviewCompleted(this, new ReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AppointData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AppointData(WorkflowType type, string target_loginname, string obj_id1, string obj_id2) {
            object[] results = this.Invoke("AppointData", new object[] {
                        type,
                        target_loginname,
                        obj_id1,
                        obj_id2});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AppointDataAsync(WorkflowType type, string target_loginname, string obj_id1, string obj_id2) {
            this.AppointDataAsync(type, target_loginname, obj_id1, obj_id2, null);
        }
        
        /// <remarks/>
        public void AppointDataAsync(WorkflowType type, string target_loginname, string obj_id1, string obj_id2, object userState) {
            if ((this.AppointDataOperationCompleted == null)) {
                this.AppointDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppointDataOperationCompleted);
            }
            this.InvokeAsync("AppointData", new object[] {
                        type,
                        target_loginname,
                        obj_id1,
                        obj_id2}, this.AppointDataOperationCompleted, userState);
        }
        
        private void OnAppointDataOperationCompleted(object arg) {
            if ((this.AppointDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppointDataCompleted(this, new AppointDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelSubmitReview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelSubmitReview(WorkflowType type, string obj_id1) {
            object[] results = this.Invoke("CancelSubmitReview", new object[] {
                        type,
                        obj_id1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelSubmitReviewAsync(WorkflowType type, string obj_id1) {
            this.CancelSubmitReviewAsync(type, obj_id1, null);
        }
        
        /// <remarks/>
        public void CancelSubmitReviewAsync(WorkflowType type, string obj_id1, object userState) {
            if ((this.CancelSubmitReviewOperationCompleted == null)) {
                this.CancelSubmitReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelSubmitReviewOperationCompleted);
            }
            this.InvokeAsync("CancelSubmitReview", new object[] {
                        type,
                        obj_id1}, this.CancelSubmitReviewOperationCompleted, userState);
        }
        
        private void OnCancelSubmitReviewOperationCompleted(object arg) {
            if ((this.CancelSubmitReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelSubmitReviewCompleted(this, new CancelSubmitReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelReview", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CancelReview(WorkflowType type, string obj_id1, string message) {
            object[] results = this.Invoke("CancelReview", new object[] {
                        type,
                        obj_id1,
                        message});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelReviewAsync(WorkflowType type, string obj_id1, string message) {
            this.CancelReviewAsync(type, obj_id1, message, null);
        }
        
        /// <remarks/>
        public void CancelReviewAsync(WorkflowType type, string obj_id1, string message, object userState) {
            if ((this.CancelReviewOperationCompleted == null)) {
                this.CancelReviewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelReviewOperationCompleted);
            }
            this.InvokeAsync("CancelReview", new object[] {
                        type,
                        obj_id1,
                        message}, this.CancelReviewOperationCompleted, userState);
        }
        
        private void OnCancelReviewOperationCompleted(object arg) {
            if ((this.CancelReviewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelReviewCompleted(this, new CancelReviewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum WorkflowType {
        
        /// <remarks/>
        测井任务通知单,
        
        /// <remarks/>
        计划任务书,
        
        /// <remarks/>
        测井作业收集信息,
        
        /// <remarks/>
        小队施工信息,
        
        /// <remarks/>
        测井现场提交信息,
        
        /// <remarks/>
        解释处理作业,
        
        /// <remarks/>
        归档入库,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C测井任务通知单))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C测井作业收集信息))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C解释处理作业))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C测井现场提交信息))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(C计划任务书))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Controller {
        
        private WorkflowData[] dataListField;
        
        private bool canSaveField;
        
        private bool canAppointDataField;
        
        private bool canSubmitReviewField;
        
        private bool canReviewField;
        
        private bool canDeleteField;
        
        private bool canCancelSubmitReviewField;
        
        private bool canCancelReviewField;
        
        /// <remarks/>
        public WorkflowData[] DataList {
            get {
                return this.dataListField;
            }
            set {
                this.dataListField = value;
            }
        }
        
        /// <remarks/>
        public bool CanSave {
            get {
                return this.canSaveField;
            }
            set {
                this.canSaveField = value;
            }
        }
        
        /// <remarks/>
        public bool CanAppointData {
            get {
                return this.canAppointDataField;
            }
            set {
                this.canAppointDataField = value;
            }
        }
        
        /// <remarks/>
        public bool CanSubmitReview {
            get {
                return this.canSubmitReviewField;
            }
            set {
                this.canSubmitReviewField = value;
            }
        }
        
        /// <remarks/>
        public bool CanReview {
            get {
                return this.canReviewField;
            }
            set {
                this.canReviewField = value;
            }
        }
        
        /// <remarks/>
        public bool CanDelete {
            get {
                return this.canDeleteField;
            }
            set {
                this.canDeleteField = value;
            }
        }
        
        /// <remarks/>
        public bool CanCancelSubmitReview {
            get {
                return this.canCancelSubmitReviewField;
            }
            set {
                this.canCancelSubmitReviewField = value;
            }
        }
        
        /// <remarks/>
        public bool CanCancelReview {
            get {
                return this.canCancelReviewField;
            }
            set {
                this.canCancelReviewField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkflowData : ModelBase {
        
        private string sOURCE_LOGINNAMEField;
        
        private string sOURCE_NAMEField;
        
        private string tARGET_LOGINNAMEField;
        
        private string tARGET_NAMEField;
        
        private WorkflowState fLOW_STATEField;
        
        private System.DateTime fLOW_TIMEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        public string SOURCE_LOGINNAME {
            get {
                return this.sOURCE_LOGINNAMEField;
            }
            set {
                this.sOURCE_LOGINNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string SOURCE_NAME {
            get {
                return this.sOURCE_NAMEField;
            }
            set {
                this.sOURCE_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string TARGET_LOGINNAME {
            get {
                return this.tARGET_LOGINNAMEField;
            }
            set {
                this.tARGET_LOGINNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string TARGET_NAME {
            get {
                return this.tARGET_NAMEField;
            }
            set {
                this.tARGET_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public WorkflowState FLOW_STATE {
            get {
                return this.fLOW_STATEField;
            }
            set {
                this.fLOW_STATEField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FLOW_TIME {
            get {
                return this.fLOW_TIMEField;
            }
            set {
                this.fLOW_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum WorkflowState {
        
        /// <remarks/>
        数据指派,
        
        /// <remarks/>
        提交审核,
        
        /// <remarks/>
        审核通过,
        
        /// <remarks/>
        审核未通过,
        
        /// <remarks/>
        新建,
        
        /// <remarks/>
        取消提交审核,
        
        /// <remarks/>
        退回审核,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkflowData))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ModelBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class C测井任务通知单 : Controller {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class C测井作业收集信息 : Controller {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class C解释处理作业 : Controller {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class C测井现场提交信息 : Controller {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class C计划任务书 : Controller {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetActiveUserWorkflowTypesCompletedEventHandler(object sender, GetActiveUserWorkflowTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveUserWorkflowTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveUserWorkflowTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WorkflowType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WorkflowType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWorkflowDataCompletedEventHandler(object sender, GetWorkflowDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWorkflowDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWorkflowDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Controller Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Controller)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SubmitReviewCompletedEventHandler(object sender, SubmitReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReviewCompletedEventHandler(object sender, ReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AppointDataCompletedEventHandler(object sender, AppointDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppointDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppointDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CancelSubmitReviewCompletedEventHandler(object sender, CancelSubmitReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelSubmitReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelSubmitReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CancelReviewCompletedEventHandler(object sender, CancelReviewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelReviewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelReviewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591