//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logging_App.A1DataInputService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A1DataInputService.WellLogInputSoap")]
    public interface WellLogInputSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataImport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DataImport(string strYear, string strWellName, System.Data.DataSet dsData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WellLogInputSoapChannel : Logging_App.A1DataInputService.WellLogInputSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WellLogInputSoapClient : System.ServiceModel.ClientBase<Logging_App.A1DataInputService.WellLogInputSoap>, Logging_App.A1DataInputService.WellLogInputSoap {
        
        public WellLogInputSoapClient() {
        }
        
        public WellLogInputSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WellLogInputSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellLogInputSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WellLogInputSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DataImport(string strYear, string strWellName, System.Data.DataSet dsData) {
            return base.Channel.DataImport(strYear, strWellName, dsData);
        }
    }
}
